{% set version = "0.12.0" %}

package:
  name: cycler
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cycler/cycler-{{ version }}.tar.gz
  sha256: 8cc3a7b4861f91b1095157f9916f748549a617046e67eb7619abed9b34d2c94a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - cycler
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/matplotlib/cycler
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Composable style cycles

extra:
  recipe-maintainers:
    - pelson
    - tacaswell
    - jankatins
    - ocefpaf
