travis:
  secure:
    BINSTAR_TOKEN: LN2iVt7PdfPv89cFFd/99ZVAfRp2VJbSOEagczge0THOUf8ZoD8fc+D3xJDWNB4aTJyKXImg0h8n9gZJHBcnEaME62vv2wlEKp0kiitDPYhncns+19KPDZSAeveRhCslHVogoa3nO04X7E3gPrLM55vVEHYucn0MN0nZCbbGVvDSa7Ctx9bJtH4XGun3bgXcK+sevZdTfmKmo0VSjggdT2sYTJsluFJXX51560KdTr1j1//uR2I9MIPlWEVqxyPyzLaVKhE1dytN+4xq7hPC4EvFWd/Vde5ZVaWGDvV8n4G7XQNL4NWwm6V0OBaj8aFw2qTM9UjTya6JlPdsORQA2qJyYZX+RVtBCO9O3ULrRgnjN5BYXbH9dQTL5fUTp1PCTmj8JcuaaK3IbbppBQFnqJCTKXx57pjtffwqDg3p8FPxAlDQV6qJ3G09qYCYMKfJCtXuYpNT4yq3q6kjReEidFoq5XCUTu/LRTfh7wi29freQZQljgeaJ/diFaqQVwZcwdt0ZcSr7lCwVeJf+uytTqefIiWJEhWGexvX4N8D1ov24vXV3BpUkHymtwZPawpyyDB0L8y8s7FEkpbsa0yUulGhyVjoj397BfNdHJuOZg/GQfAdBjwDqXy+/ne/aHtCyftSPTUcS9nX9pvc4//ar4CM2VB6VKZSvcsnrgXTr1w=
appveyor:
  secure:
    BINSTAR_TOKEN: KDvUkPrcdKmV2MxakkyQlrLA0rE/6WSuXxD42UezzZjCB0TRqnnOeebSW03/SnFP
